/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChatsRouteImport } from './routes/_app/chats'
import { Route as AppChatsIndexRouteImport } from './routes/_app/chats.index'
import { Route as AppQueriesNewRouteImport } from './routes/_app/queries.new'
import { Route as AppQueriesIdRouteImport } from './routes/_app/queries.$id'
import { Route as AppProfileIdRouteImport } from './routes/_app/profile.$id'
import { Route as AppChatsIdRouteImport } from './routes/_app/chats.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsIndexRoute = AppChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChatsRoute,
} as any)
const AppQueriesNewRoute = AppQueriesNewRouteImport.update({
  id: '/queries/new',
  path: '/queries/new',
  getParentRoute: () => AppRoute,
} as any)
const AppQueriesIdRoute = AppQueriesIdRouteImport.update({
  id: '/queries/$id',
  path: '/queries/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIdRoute = AppProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsIdRoute = AppChatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppChatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chats': typeof AppChatsRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/chats/$id': typeof AppChatsIdRoute
  '/profile/$id': typeof AppProfileIdRoute
  '/queries/$id': typeof AppQueriesIdRoute
  '/queries/new': typeof AppQueriesNewRoute
  '/chats/': typeof AppChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/chats/$id': typeof AppChatsIdRoute
  '/profile/$id': typeof AppProfileIdRoute
  '/queries/$id': typeof AppQueriesIdRoute
  '/queries/new': typeof AppQueriesNewRoute
  '/chats': typeof AppChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/chats': typeof AppChatsRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/chats/$id': typeof AppChatsIdRoute
  '/_app/profile/$id': typeof AppProfileIdRoute
  '/_app/queries/$id': typeof AppQueriesIdRoute
  '/_app/queries/new': typeof AppQueriesNewRoute
  '/_app/chats/': typeof AppChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/chats'
    | '/dashboard'
    | '/settings'
    | '/chats/$id'
    | '/profile/$id'
    | '/queries/$id'
    | '/queries/new'
    | '/chats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/settings'
    | '/chats/$id'
    | '/profile/$id'
    | '/queries/$id'
    | '/queries/new'
    | '/chats'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/chats'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/chats/$id'
    | '/_app/profile/$id'
    | '/_app/queries/$id'
    | '/_app/queries/new'
    | '/_app/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats': {
      id: '/_app/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats/': {
      id: '/_app/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof AppChatsIndexRouteImport
      parentRoute: typeof AppChatsRoute
    }
    '/_app/queries/new': {
      id: '/_app/queries/new'
      path: '/queries/new'
      fullPath: '/queries/new'
      preLoaderRoute: typeof AppQueriesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queries/$id': {
      id: '/_app/queries/$id'
      path: '/queries/$id'
      fullPath: '/queries/$id'
      preLoaderRoute: typeof AppQueriesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$id': {
      id: '/_app/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AppProfileIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chats/$id': {
      id: '/_app/chats/$id'
      path: '/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof AppChatsIdRouteImport
      parentRoute: typeof AppChatsRoute
    }
  }
}

interface AppChatsRouteChildren {
  AppChatsIdRoute: typeof AppChatsIdRoute
  AppChatsIndexRoute: typeof AppChatsIndexRoute
}

const AppChatsRouteChildren: AppChatsRouteChildren = {
  AppChatsIdRoute: AppChatsIdRoute,
  AppChatsIndexRoute: AppChatsIndexRoute,
}

const AppChatsRouteWithChildren = AppChatsRoute._addFileChildren(
  AppChatsRouteChildren,
)

interface AppRouteChildren {
  AppChatsRoute: typeof AppChatsRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppProfileIdRoute: typeof AppProfileIdRoute
  AppQueriesIdRoute: typeof AppQueriesIdRoute
  AppQueriesNewRoute: typeof AppQueriesNewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatsRoute: AppChatsRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppProfileIdRoute: AppProfileIdRoute,
  AppQueriesIdRoute: AppQueriesIdRoute,
  AppQueriesNewRoute: AppQueriesNewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
